### ISSUE TITLE
timezone

### ISSUE THREAD

**Issue by Crypt97** [matcracker/BedcoreProtect#18]
### Issue description

- Expected result: What were you expecting to happen?
- Actual result: What actually happened?

### Steps to reproduce the issue
1. Put plugin for plugins folder
2. start server, watch console

### OS and versions

* BedcoreProtect:

* PocketMine-MP: 
* PHP: 7.x
* Server OS: Windws 10 64 Bit
* Game version: Win10

### Plugins

- If you remove all plugins, does the issue still occur?
- If the issue is **not** reproducible without plugins:
  - Can you provide sample, *minimal* reproducing code for the issue? If so, paste it in the bottom section

### Crashdump, backtrace or other files
20:14:39 <Server thread/Critical> ErrorException: "Undefined index: timezone" (EXCEPTION) in "plugins/BedcoreProtect-experimental/src/matcracker/BedcoreProtect/utils/ConfigParser" at line 291
20:14:39 <Server thread/Debug> #0 plugins/BedcoreProtect-experimental/src/matcracker/BedcoreProtect/utils/ConfigParser(291): pocketmine\utils\Utils::errorExceptionHandler(integer 8, string[25] Undefined index: timezone, string[133] C:\Users\crypt\Desktop\Mapp..k\Altay2-master\plugins\BedcoreProtect-experimental, integer 291, array[0])
20:14:39 <Server thread/Debug> #1 plugins/BedcoreProtect-experimental/src/matcracker/BedcoreProtect/utils/ConfigParser(281): matcracker\BedcoreProtect\utils\ConfigParser->getTimezone()
20:14:39 <Server thread/Debug> #2 plugins/BedcoreProtect-experimental/src/matcracker/BedcoreProtect/Main(108): matcracker\BedcoreProtect\utils\ConfigParser->validate()
20:14:39 <Server thread/Debug> #3 src/pocketmine/plugin/PluginManager(180): matcracker\BedcoreProtect\Main->onLoad()
20:14:39 <Server thread/Debug> #4 src/pocketmine/plugin/PluginManager(335): pocketmine\plugin\PluginManager->loadPlugin(string[80] C:\Users\crypt\Desktop\Mapp..k\Altay2-master\plugins\BedcoreProtect-experimental, array[1])
20:14:39 <Server thread/Debug> #5 plugins/PocketMine-DevTools_dev-1.phar/src/DevTools/DevTools(49): pocketmine\plugin\PluginManager->loadPlugins(string[53] C:\Users\crypt\Desktop\Mapp..k\Altay2-master\plugins\, array[1])
20:14:39 <Server thread/Debug> #6 src/pocketmine/plugin/PluginBase(115): DevTools\DevTools->onEnable()
20:14:39 <Server thread/Debug> #7 src/pocketmine/plugin/PluginManager(541): pocketmine\plugin\PluginBase->setEnabled(boolean 1)
20:14:39 <Server thread/Debug> #8 src/pocketmine/Server(1894): pocketmine\plugin\PluginManager->enablePlugin(object DevTools\DevTools)
20:14:39 <Server thread/Debug> #9 src/pocketmine/Server(1880): pocketmine\Server->enablePlugin(object DevTools\DevTools)
20:14:39 <Server thread/Debug> #10 src/pocketmine/Server(1605): pocketmine\Server->enablePlugins(integer 0)
20:14:39 <Server thread/Debug> #11 src/pocketmine/PocketMine(273): pocketmine\Server->__construct(object BaseClassLoader, object pocketmine\utils\MainLogger, string[45] C:\Users\crypt\Desktop\Mapp..k\Altay2-master\, string[53] C:\Users\crypt\Desktop\Mapp..k\Altay2-master\plugins\)
20:14:39 <Server thread/Debug> #12 src/pocketmine/PocketMine(296): pocketmine\server()
20:14:39 <Server thread/Debug> #13 (11): require(string[100] phar://C:/Users/crypt/Desktop/Mapp..k/Altay2-master/PocketMine-MP.phar/src/pocke)
20:14:39 <Server thread/Critical> Could not load plugin 'BedcoreProtect'

**Comment by matcracker** [comment]
Which version of plugin?

**Comment by Crypt97** [comment]
Sorry no bug I made a mistake
