### ISSUE TITLE
Error onEnable

### ISSUE THREAD

**Issue by Shelly7w7** [matcracker/BedcoreProtect#2]
### Issue description

- Expected result: What were you expecting to happen?
To enable this on load
- Actual result: What actually happened?
Doesnt loads, gives some config errors
### Steps to reproduce the issue
1. ... PUt the .phar in your plugins folder
2. ... And start the server.

### OS and versions

* PocketMine-MP: 3.8.1
* PHP: 7.2
* Server OS: Windows
* Game version: 1.11.3

### Plugins

Devtools, BedcoreProtect
- If you remove all plugins, does the issue still occur?
Yes
- If the issue is **not** reproducible without plugins:
  - Can you provide sample, *minimal* reproducing code for the issue? 
[Server thread/INFO]: Enabling BedcoreProtect v0.1.0
[08:58:00] [Server thread/WARNING]: [BedcoreProtect] Configuration's file is not correct.
[08:58:00] [Server thread/WARNING]: [BedcoreProtect] database.mysql.schema must not be empty
[08:58:00] [Server thread/INFO]: Disabling BedcoreProtect v0.1.0

**Comment by matcracker** [comment]
You need to insert the database name (called schema on config.yml) into the config.yml file.
