### ISSUE TITLE
issue upgrading db with a new build

### ISSUE THREAD

**Issue by teracube** [matcracker/BedcoreProtect#29]
### Issue description
I try upgrade plugin 
BedcoreProtect_dev-299.phar =) BedcoreProtect_dev-305.phar
new build enable then disable with message error :
"Your database is running a higher version than BedcoreProtect. Please update the plugin if you want to use it."

- Expected result: What were you expecting to happen?
- Actual result: What actually happened?
db refuse to upgrade
### Steps to reproduce the issue
1. ...update BedcoreProtect_dev-299.phar =) BedcoreProtect_dev-302.phar
2. ...start server

### OS and versions

* BedcoreProtect: 0.6.1

* PocketMine-MP: 3.12.2
* PHP:
* Server OS:
* Game version: PE/Win10 (delete as appropriate)

### Plugins

- If you remove all plugins, does the issue still occur?
- If the issue is **not** reproducible without plugins:
  - Can you provide sample, *minimal* reproducing code for the issue? If so, paste it in the bottom section

### Crashdump, backtrace or other files

```
2020-05-22 [07:15:33] [Server thread/INFO]: Loading BedcoreProtect v0.6.1
2020-05-22 [07:15:33] [Server thread/INFO]: Enabling BedcoreProtect v0.6.1
2020-05-22 [07:15:33] [Server thread/WARNING]: [BedcoreProtect] Your database is running a higher version than BedcoreProtect. Please update the plugin if you want to use it.
2020-05-22 [07:15:33] [Server thread/INFO]: Disabling BedcoreProtect v0.6.1

```

**Comment by matcracker** [comment]
Sorry about it. I'm working on v0.6.2 (not finished yet) and by pushing the database patches and I didn't expect this issue. To fix the problem, update to next build 306 and restore the backup of database v0.6.1 (you will find it inside the plugin data folder of plugin).
