### ISSUE TITLE
Error Level: matcracker\BedcoreProtect\libs\SOFe\AwaitGenerator\AwaitException line #377

### ISSUE THREAD

**Issue by brospaghetti9** [matcracker/BedcoreProtect#31]
### Issue description

-My server just crashes randomly and I think It has something to do with the plugin Burger Spawers but the crash archive says its at this directory matcracker\BedcoreProtect\libs\SOFe\AwaitGenerator\AwaitException in bedcore protect at line #377

### Steps to reproduce the issue
IDK what this is lol.

### OS and versions
< api is 3.14.2
os version is ubuntu linux desktop 18.04 running a webserver software for multiple servers

Crash Archive- https://crash.pmmp.io/view/4220160

**Comment by matcracker** [comment]
This issue should be related to #25, already fixed in v0.6.1. Please update the plugin from poggit: https://poggit.pmmp.io/p/BedcoreProtect/
