### ISSUE TITLE
Tengo un error y es que hace que el servidor Crashee, no lo cierra ni nada, solo deshabilita algunos Plugins y no permite que entren usuarios.

### ISSUE THREAD

**Issue by ghost** [matcracker/BedcoreProtect#41]
### Issue description

- Expected result: What were you expecting to happen?
- Actual result: What actually happened?

### Steps to reproduce the issue
1. ... Instalar el Complemento
2. ... Y en un rato debería suceder

### OS and versions

* BedcoreProtect:

* PocketMine-MP:
* PHP:
* Server OS:
* Game version: PE/Win10 (delete as appropriate)

### Plugins

- If you remove all plugins, does the issue still occur?
- If the issue is **not** reproducible without plugins:
  - Can you provide sample, *minimal* reproducing code for the issue? If so, paste it in the bottom section

**Comment by matcracker** [comment]
Please fill the form correctly and in English. Thank you.

**Comment by soyilai** [comment]
Hola bro, nos podrias dar mas informafion del tema? Lo prefeririamos en inglés, gracias :)
