### ISSUE TITLE
Item meta goes out of range

### ISSUE THREAD

**Issue by Giulizo** [matcracker/BedcoreProtect#44]
### Issue description

Hi there! I hope you're doing well. Unfortunately, I don't know how to contact your support. I have installed your plugin (https://github.com/matcracker/BedcoreProtect) and unfortunately get the following error message:

https://pastebin.com/EX2cEaF2

Could you please help me out?
Thank you in advance.

### Steps to reproduce the issue
1. Installation and use of the plugin

### OS and versions

* BedcoreProtect:

* PocketMine-MP: 3.19.0
* PHP: 7.3
* Server OS:
* Game version:Win10 (delete as appropriate)

### Plugins

- If you remove all plugins, does the issue still occur?
- If the issue is **not** reproducible without plugins:
  - Can you provide sample, *minimal* reproducing code for the issue? If so, paste it in the bottom section

**Comment by matcracker** [comment]
Hi, thank you for your report. Can you provide the plugin version?
