### ISSUE TITLE
Log players gt that opens a chest 

### ISSUE THREAD

**Issue by SpadeOfAces525** [matcracker/BedcoreProtect#48]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by matcracker** [comment]
can you explain your request better? From the title it looks like a feature that already exists in the plugin.

**Comment by matcracker** [comment]
I close the issue. If more information are provided I'll reopen it.
