### ISSUE TITLE
Issues for PMMP5

### ISSUE THREAD

**Issue by cherrychip8293** [matcracker/BedcoreProtect#67]
### Issue description

I didn't want anything to happen and I wanted it to work

### Steps to reproduce the issue
1. Install the block
2. Enter /bcpit to check the log
3. After that, try to erase the installed block after entering /bcpit again, and an error will occur

### OS and versions

* BedcoreProtect: 1.1.0

* PocketMine-MP: 5.0.0-BETA4
* PHP: 8.2.6
* Server OS: Linux
* Game version: Win10

### Plugins

- If you remove all plugins, does the issue still occur?
- If the issue is **not** reproducible without plugins:
  - Can you provide sample, *minimal* reproducing code for the issue? If so, paste it in the bottom section
![image](https://github.com/matcracker/BedcoreProtect/assets/82744478/9f41498f-21a9-4bdf-bfee-3b28e3dd3841)

### Crashdump, backtrace or other files
Error: "Call to undefined method pocketmine\block\Op
aque::isSameType()" (EXCEPTION) in "plugins/BedcoreProtect-pm5.phar/src/matcracker/BedcoreProtect/storage/queries/BlocksQueries" at line 157
--- Stack trace ---
  #0 pmsrc/src/scheduler/ClosureTask(57): matcracker\BedcoreProtect\storage\queries\BlocksQueries->matcracker\BedcoreProtect\storage\queries\{closure}()
  #1 pmsrc/src/scheduler/TaskHandler(113): pocketmine\scheduler\ClosureTask->onRun()
  #2 pmsrc/src/scheduler/TaskScheduler(137): pocketmine\scheduler\TaskHandler->run()
  #3 pmsrc/src/plugin/PluginManager(530): pocketmine\scheduler\TaskScheduler->mainThreadHeartbeat(int 190)
  #4 pmsrc/src/Server(1782): pocketmine\plugin\PluginManager->tickSchedulers(int 190)
  #5 pmsrc/src/Server(1671): pocketmine\Server->tick()
  #6 pmsrc/src/Server(1063): pocketmine\Server->tickProcessor()
  #7 pmsrc/src/PocketMine(334): pocketmine\Server->__construct(object pocketmine\thread\ThreadSafeClassLoader#3, object pocketmine\utils\MainLogger#6, string[9] /root/pm/, string[17] /root/pm/plugins/)
  #8 pmsrc/src/PocketMine(357): pocketmine\server()
  #9 pmsrc(11): require(string[53] phar:///root/pm/PocketMine-MP.phar/src/PocketMine.php)
--- End of exception information ---

**Comment by matcracker** [comment]
The plugin does not support the PM5 BETA 4 yet

**Comment by matcracker** [comment]
Fixed by f5d0365
