### ISSUE TITLE
sql Communication error

### ISSUE THREAD

**Issue by cherrychip8293** [matcracker/BedcoreProtect#69]
### Issue description

- Expected result: What were you expecting to happen?
- Actual result: What actually happened?

### Steps to reproduce the issue
1. Set the data storage method with mysql
2. Afterwards, try to do any action using the rollback function, and you'll get an error

### OS and versions

* BedcoreProtect: 1.1.0

* PocketMine-MP: 5.0.0 - BETA4
* PHP: 8.2
* Server OS: linux
* Game version: Win10 

### Plugins

 BedcoreProtect v1.1.0, BossPlugin v1.0.3, BuilderTools v2.0.0-dev, CaveGenerator v1.0.0, CustomItemLoader v3.2.0, EquipmentManager v1.0.2, Mine v1.0.0, MonsterPlugin v1.0.15, RPGCore v1.1.4, Slapper v3.0.0, UpgradeTool v1.0.0, WarpCore v2.0.0, WorldManager v1.2.3-Adam, libItemRegistrar v1.0.0

- If you remove all plugins, does the issue still occur?
- If the issue is **not** reproducible without plugins:
  - Can you provide sample, *minimal* reproducing code for the issue? If so, paste it in the bottom section

### Crashdump, backtrace or other files

Fatal error: Uncaught mysqli_sql_exception: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'FROM log_history INNER JOIN blocks_log ON log_history.log_id = history_id
      ' at line 8 in phar:///root/pm/plugins/BedcoreProtect-pm5.phar/src/_8a2a3e91c4e22a1e8c9apoggit/libasynql/mysqli/MysqliThread.php:140
Stack trace:
#0 phar:///root/pm/plugins/BedcoreProtect-pm5.phar/src/_8a2a3e91c4e22a1e8c9apoggit/libasynql/mysqli/MysqliThread.php(140): mysqli->prepare('SELECT log_id, ...')
#1 phar:///root/pm/plugins/BedcoreProtect-pm5.phar/src/_8a2a3e91c4e22a1e8c9apoggit/libasynql/base/SqlSlaveThread.php(89): _8a2a3e91c4e22a1e8c9apoggit\libasynql\mysqli\MysqliThread->executeQuery(Object(mysqli), 3, 'SELECT log_id, ...', Array)
#2 phar:///root/pm/PocketMine-MP.phar/src/thread/CommonThreadPartsTrait.php(96): _8a2a3e91c4e22a1e8c9apoggit\libasynql\base\SqlSlaveThread->onRun()
#3 [internal function]: pocketmine\thread\Thread->run()
#4 {main}
  thrown in phar:///root/pm/plugins/BedcoreProtect-pm5.phar/src/_8a2a3e91c4e22a1e8c9apoggit/libasynql/mysqli/MysqliThread.php on line 140

**Comment by matcracker** [comment]
Thanks for report, issue fixed by e1cb4f746209f3ba68f7ddb82ed203e6002ca7c8
