### ISSUE TITLE
Crash when stopping the server while database is loading

### ISSUE THREAD

**Issue by cherrychip8293** [matcracker/BedcoreProtect#73]
### Issue description

- Expected result: What were you expecting to happen?
- Actual result: What actually happened?

### Steps to reproduce the issue
I don't know why the error occurs, but all I can see is that it occurs when the server shuts down

### OS and versions

* BedcoreProtect:

* PocketMine-MP:
* PHP:
* Server OS:
* Game version: PE/Win10 (delete as appropriate)

### Plugins

 플러그인 (60): AntiFallDamage v2.0.2, AntiHunger v1.0.0, ArmorStandLoader v1.0.0, AutoPickup v1.0.0, AutoPlant v1.2.0, BanStay v1.0.0, BasicItem v1.0.0, BedcoreProtect v1.1.0, BlazinFly v1.9.0, BlockGenerator v0.0.2, BossPlugin v1.0.9, CancelLeaveDecay v1.0.0, CaveGenerator v1.0.0, ChestLocker v1.0.0, CropGrowth v2.0.4+dev, CrushGuild v1.0.3, CustomItemLoader v3.3.0, DEVirion v1.3.0, DiceGambling v1.0.0, EquipmentManager v1.0.2, Help v1.0.0, HitParticle v0.0.3, HologramAPI v0.0.1, HotTimeManager v1.0.0, InvSee v2.2.5, InventoryMenuAPI v0.0.1, IslandPlugin v1.0.9, ItemName v1.0.0, KeepInventory v3.0.0, MarketPlugin v1.0.0, Mine v1.0.0, MineA v1.0.3, MinePlus v1.0.0, MoneyCore v1.0.4, MonsterPlugin v1.0.19, MultiWorld v1.8.0-ALPHA1, NoDeathMessage v1.0.0, NoFarmlandDecay v0.0.2, PersonaAdapter v2.0.0, PrefixAPI v0.0.3, RInfo v1.0.0, RMessage v1.0.2, RPGCore v1.1.4, RankAPI v0.0.2, Repairs v0.0.1, SimpleAttendance v1.0.0, SimpleReboot v1.0.0, SimpleSneakInfo v1.0.0, Slapper v3.0.0, Stalker v2.1.1, Trigger v1.0.0, UpgradeTool v1.0.0, VanillaElytra v1.7.0, VanillaHopper v2.2.1, Warn v1.0.0, WarpCore v2.0.0, WeaponSkill v1.0.6, WorldManager v1.2.3-Adam, Yatoo v1.0.0, libItemRegistrar v1.0.0

- If you remove all plugins, does the issue still occur?
- If the issue is **not** reproducible without plugins:
  - Can you provide sample, *minimal* reproducing code for the issue? If so, paste it in the bottom section

### Crashdump, backtrace or other files

pocketmine\plugin\PluginException: "Plugin attempted to register matcracker\BedcoreProtect\listeners\BlockListener while not enabled" (EXCEPTION) in "pmsrc/src/plugin/PluginManager" at line 590
--- Stack trace ---
  #0 plugins/BedcoreProtect.phar/src/matcracker/BedcoreProtect/Main(160): pocketmine\plugin\PluginManager->registerEvents(object matcracker\BedcoreProtect\listeners\BlockListener#161986, object matcracker\BedcoreProtect\Main#64336)
  #1 plugins/BedcoreProtect.phar/src/matcracker/BedcoreProtect/libs/SOFe/AwaitGenerator/Await(570): matcracker\BedcoreProtect\Main->matcracker\BedcoreProtect\{closure}(null)
  #2 plugins/BedcoreProtect.phar/src/matcracker/BedcoreProtect/libs/SOFe/AwaitGenerator/Await(340): matcracker\BedcoreProtect\libs\SOFe\AwaitGenerator\Await->resolve(null)
  #3 plugins/BedcoreProtect.phar/src/matcracker/BedcoreProtect/libs/SOFe/AwaitGenerator/Await(317): matcracker\BedcoreProtect\libs\SOFe\AwaitGenerator\Await->wakeup(object Closure#190640)
  #4 plugins/BedcoreProtect.phar/src/matcracker/BedcoreProtect/libs/SOFe/AwaitGenerator/Await(552): matcracker\BedcoreProtect\libs\SOFe\AwaitGenerator\Await->wakeupFlat(object Closure#190640)
  #5 plugins/BedcoreProtect.phar/src/matcracker/BedcoreProtect/libs/SOFe/AwaitGenerator/AwaitChild(52): matcracker\BedcoreProtect\libs\SOFe\AwaitGenerator\Await->recheckPromiseQueue(object matcracker\BedcoreProtect\libs\SOFe\AwaitGenerator\AwaitChild#162554)
  #6 plugins/BedcoreProtect.phar/src/matcracker/BedcoreProtect/libs/poggit/libasynql/base/DataConnectorImpl(165): matcracker\BedcoreProtect\libs\SOFe\AwaitGenerator\AwaitChild->resolve(array[2])
  #7 plugins/BedcoreProtect.phar/src/matcracker/BedcoreProtect/libs/poggit/libasynql/base/DataConnectorImpl(156): matcracker\BedcoreProtect\libs\poggit\libasynql\base\DataConnectorImpl::matcracker\BedcoreProtect\libs\poggit\libasynql\base\{closure}(int 0, int 0)
  #8 plugins/BedcoreProtect.phar/src/matcracker/BedcoreProtect/libs/poggit/libasynql/base/DataConnectorImpl(181): matcracker\BedcoreProtect\libs\poggit\libasynql\base\DataConnectorImpl::matcracker\BedcoreProtect\libs\poggit\libasynql\base\{closure}(object matcracker\BedcoreProtect\libs\poggit\libasynql\result\SqlInsertResult#238554)
  #9 plugins/BedcoreProtect.phar/src/matcracker/BedcoreProtect/libs/poggit/libasynql/base/DataConnectorImpl(239): matcracker\BedcoreProtect\libs\poggit\libasynql\base\DataConnectorImpl::matcracker\BedcoreProtect\libs\poggit\libasynql\base\{closure}(array[1])
  #10 plugins/BedcoreProtect.phar/src/matcracker/BedcoreProtect/libs/poggit/libasynql/base/SqlThreadPool(111): matcracker\BedcoreProtect\libs\poggit\libasynql\base\DataConnectorImpl->matcracker\BedcoreProtect\libs\poggit\libasynql\base\{closure}(array[1])
  #11 plugins/BedcoreProtect.phar/src/matcracker/BedcoreProtect/libs/poggit/libasynql/base/DataConnectorImpl(322): matcracker\BedcoreProtect\libs\poggit\libasynql\base\SqlThreadPool->readResults(array[1])
  #12 plugins/BedcoreProtect.phar/src/matcracker/BedcoreProtect/libs/poggit/libasynql/base/DataConnectorImpl(317): matcracker\BedcoreProtect\libs\poggit\libasynql\base\DataConnectorImpl->checkResults()
  #13 plugins/BedcoreProtect.phar/src/matcracker/BedcoreProtect/storage/DatabaseManager(137): matcracker\BedcoreProtect\libs\poggit\libasynql\base\DataConnectorImpl->waitAll()
  #14 plugins/BedcoreProtect.phar/src/matcracker/BedcoreProtect/Main(177): matcracker\BedcoreProtect\storage\DatabaseManager->disconnect()
  #15 pmsrc/src/plugin/PluginBase(120): matcracker\BedcoreProtect\Main->onDisable()
  #16 pmsrc/src/plugin/PluginManager(519): pocketmine\plugin\PluginBase->onEnableStateChange(false)
  #17 pmsrc/src/plugin/PluginManager(501): pocketmine\plugin\PluginManager->disablePlugin(object matcracker\BedcoreProtect\Main#64336)
  #18 pmsrc/src/Server(1456): pocketmine\plugin\PluginManager->disablePlugins()
  #19 pmsrc/src/Server(1064): pocketmine\Server->forceShutdown()
  #20 pmsrc/src/PocketMine(334): pocketmine\Server->__construct(object pocketmine\thread\ThreadSafeClassLoader#3, object pocketmine\utils\MainLogger#6, string[14] /home/user/pm/, string[22] /home/user/pm/plugins/)
  #21 pmsrc/src/PocketMine(357): pocketmine\server()
  #22 pmsrc(11): require(string[58] phar:///home/user/pm/PocketMine-MP.phar/src/PocketMine.php)
--- End of exception information ---

**Comment by matcracker** [comment]
I'm not able to reproduce the error, can you provide more steps?

**Comment by matcracker** [comment]
Hi, I have found the cause of issue. It happens when you stop the plugin while is loading the database. You will find the fix in the next release. Thanks for the report.
