### ISSUE TITLE
Server Closed error

### ISSUE THREAD

**Issue by cherrychip8293** [matcracker/BedcoreProtect#74]
PHP : 8.2
API : 5.1.2
Server OS : linux

 pocketmine\plugin\PluginException: "Plugin attempted to register matcracker\BedcoreProtect\listeners\BlockListener while not enabled" (EXCEPTION) in "pmsrc/src/plugin/PluginManager" at line 590
--- Stack trace ---
  #0 plugins/BedcoreProtect.phar/src/matcracker/BedcoreProtect/Main(160): pocketmine\plugin\PluginManager->registerEvents(object matcracker\BedcoreProtect\listeners\BlockListener#70775, object matcracker\BedcoreProtect\Main#60710)
  #1 plugins/BedcoreProtect.phar/src/matcracker/BedcoreProtect/libs/SOFe/AwaitGenerator/Await(570): matcracker\BedcoreProtect\Main->matcracker\BedcoreProtect\{closure}(null)
  #2 plugins/BedcoreProtect.phar/src/matcracker/BedcoreProtect/libs/SOFe/AwaitGenerator/Await(340): matcracker\BedcoreProtect\libs\SOFe\AwaitGenerator\Await->resolve(null)
  #3 plugins/BedcoreProtect.phar/src/matcracker/BedcoreProtect/libs/SOFe/AwaitGenerator/Await(317): matcracker\BedcoreProtect\libs\SOFe\AwaitGenerator\Await->wakeup(object Closure#251076)
  #4 plugins/BedcoreProtect.phar/src/matcracker/BedcoreProtect/libs/SOFe/AwaitGenerator/Await(552): matcracker\BedcoreProtect\libs\SOFe\AwaitGenerator\Await->wakeupFlat(object Closure#251076)
  #5 plugins/BedcoreProtect.phar/src/matcracker/BedcoreProtect/libs/SOFe/AwaitGenerator/AwaitChild(52): matcracker\BedcoreProtect\libs\SOFe\AwaitGenerator\Await->recheckPromiseQueue(object matcracker\BedcoreProtect\libs\SOFe\AwaitGenerator\AwaitChild#58)
  #6 plugins/BedcoreProtect.phar/src/matcracker/BedcoreProtect/libs/poggit/libasynql/base/DataConnectorImpl(165): matcracker\BedcoreProtect\libs\SOFe\AwaitGenerator\AwaitChild->resolve(array[2])
  #7 plugins/BedcoreProtect.phar/src/matcracker/BedcoreProtect/libs/poggit/libasynql/base/DataConnectorImpl(156): matcracker\BedcoreProtect\libs\poggit\libasynql\base\DataConnectorImpl::matcracker\BedcoreProtect\libs\poggit\libasynql\base\{closure}(int 0, int 0)
  #8 plugins/BedcoreProtect.phar/src/matcracker/BedcoreProtect/libs/poggit/libasynql/base/DataConnectorImpl(181): matcracker\BedcoreProtect\libs\poggit\libasynql\base\DataConnectorImpl::matcracker\BedcoreProtect\libs\poggit\libasynql\base\{closure}(object matcracker\BedcoreProtect\libs\poggit\libasynql\result\SqlInsertResult#177755)
  #9 plugins/BedcoreProtect.phar/src/matcracker/BedcoreProtect/libs/poggit/libasynql/base/DataConnectorImpl(239): matcracker\BedcoreProtect\libs\poggit\libasynql\base\DataConnectorImpl::matcracker\BedcoreProtect\libs\poggit\libasynql\base\{closure}(array[1])
  #10 plugins/BedcoreProtect.phar/src/matcracker/BedcoreProtect/libs/poggit/libasynql/base/SqlThreadPool(111): matcracker\BedcoreProtect\libs\poggit\libasynql\base\DataConnectorImpl->matcracker\BedcoreProtect\libs\poggit\libasynql\base\{closure}(array[1])
  #11 plugins/BedcoreProtect.phar/src/matcracker/BedcoreProtect/libs/poggit/libasynql/base/DataConnectorImpl(322): matcracker\BedcoreProtect\libs\poggit\libasynql\base\SqlThreadPool->readResults(array[1])
  #12 plugins/BedcoreProtect.phar/src/matcracker/BedcoreProtect/libs/poggit/libasynql/base/DataConnectorImpl(317): matcracker\BedcoreProtect\libs\poggit\libasynql\base\DataConnectorImpl->checkResults()
  #13 plugins/BedcoreProtect.phar/src/matcracker/BedcoreProtect/storage/DatabaseManager(137): matcracker\BedcoreProtect\libs\poggit\libasynql\base\DataConnectorImpl->waitAll()
  #14 plugins/BedcoreProtect.phar/src/matcracker/BedcoreProtect/Main(177): matcracker\BedcoreProtect\storage\DatabaseManager->disconnect()
  #15 pmsrc/src/plugin/PluginBase(120): matcracker\BedcoreProtect\Main->onDisable()
  #16 pmsrc/src/plugin/PluginManager(519): pocketmine\plugin\PluginBase->onEnableStateChange(false)
  #17 pmsrc/src/plugin/PluginManager(501): pocketmine\plugin\PluginManager->disablePlugin(object matcracker\BedcoreProtect\Main#60710)
  #18 pmsrc/src/Server(1456): pocketmine\plugin\PluginManager->disablePlugins()
  #19 pmsrc/src/Server(1064): pocketmine\Server->forceShutdown()
  #20 pmsrc/src/PocketMine(334): pocketmine\Server->__construct(object pocketmine\thread\ThreadSafeClassLoader#3, object pocketmine\utils\MainLogger#6, string[14] /home/user/pm/, string[22] /home/user/pm/plugins/)
  #21 pmsrc/src/PocketMine(357): pocketmine\server()
  #22 pmsrc(11): require(string[58] phar:///home/user/pm/PocketMine-MP.phar/src/PocketMine.php)
--- End of exception information ---

**Comment by matcracker** [comment]
Duplicated of #73
