### ISSUE TITLE
Error when logging entity killed by block not present in the database

### ISSUE THREAD

**Issue by StefanFox-Dev** [matcracker/BedcoreProtect#75]
### Issue description

- Expected result: What were you expecting to happen?
- Actual result: What actually happened?
`Fatal error: Uncaught ErrorException: SQLite3Stmt::execute(): Unable to execute
statement: NOT NULL constraint failed: log_history.who in phar:///root/plugins/BedcoreProtect_dev-517.phar/src/matcracker/BedcoreProtect/libs/poggit/libasynql/sqlite3/Sqlite3Thread.php:90
Stack trace:
#0 [internal function]: pocketmine\errorhandler\ErrorToExceptionHandler::handle(2, 'SQLite3Stmt::ex...', 'phar:///root/su...', 90)
#1 phar:///root/plugins/BedcoreProtect_dev-517.phar/src/matcracker/BedcoreProtect/libs/poggit/libasynql/sqlite3/Sqlite3Thread.php(90): SQLite3Stmt->execute()
#2 phar:///root/plugins/BedcoreProtect_dev-517.phar/src/matcracker/BedcoreProtect/libs/poggit/libasynql/base/SqlSlaveThread.php(86): matcracker\BedcoreProtect\libs\poggit\libasynql\sqlite3\Sqlite3Thread->executeQuery(Object(SQLite3), 2, 'INSERT INTO "lo...', Array)
#3 /root/src/thread/CommonThreadPartsTrait.php(96): matcracker\BedcoreProtect\libs\poggit\libasynql\base\SqlSlaveThread->onRun()
#4 [internal function]: pocketmine\thread\Thread->run()
#5 {main}
  thrown in phar:///root/plugins/BedcoreProtect_dev-517.phar/src/matcracker/BedcoreProtect/libs/poggit/libasynql/sqlite3/Sqlite3Thread.php on line 90`

### OS and versions

* BedcoreProtect:

* PocketMine-MP: 5.1.3
* PHP: 8.2
* Server OS: Ubuntu 22
* Game version: PE/Win10

### Plugins

- If you remove all plugins, does the issue still occur?
- If the issue is **not** reproducible without plugins:
  - Can you provide sample, *minimal* reproducing code for the issue? If so, paste it in the bottom section

**Comment by matcracker** [comment]
Hi, can you provide some steps to reproduce the error?

**Comment by StefanFox-Dev** [comment]
xd, just saw an error. there is no crash

**Comment by matcracker** [comment]
I probably fixed the issue with commit 00df2fa. Let me know if it happens again. 

Thanks for report.
