### ISSUE TITLE
Problem shutting down plug-in when abnormal

### ISSUE THREAD

**Issue by cherrychip8293** [matcracker/BedcoreProtect#77]
If the server fails and shuts down abnormally, the plug-in does not shut down when using the mysql connection, resulting in a bug in which the server is maintained

**Comment by matcracker** [comment]
Hi, can you explain better your case? I tried to reproduce it but without any problem. Thank you.

**Comment by vkamz597** [comment]
If you intentionally try to cause an error in a plug-in other than that plug-in, there will be a delay problem

**Comment by cherrychip8293** [comment]
> Hi, can you explain better your case? I tried to reproduce it but without any problem. Thank you.

If you intentionally try to cause an error in a plug-in other than that plug-in, there will be a delay problem

**Comment by matcracker** [comment]
> > Hi, can you explain better your case? I tried to reproduce it but without any problem. Thank you.
> 
> If you intentionally try to cause an error in a plug-in other than that plug-in, there will be a delay problem
> 
Ok, I'll try later.

**Comment by matcracker** [comment]
I'm not able to reproduce the issue... Does it happen after a while the server is on?

**Comment by matcracker** [comment]
Try to enable the debug-mode option in the config.yml of the plugin in order to see if something is printing during the shutdown.

**Comment by matcracker** [comment]
Maybe it's related to https://github.com/poggit/libasynql/issues/85#issuecomment-1651751936

**Comment by matcracker** [comment]
Fixed in v1.2.3
