### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by cherrychip8293** [matcracker/BedcoreProtect#78]
SOFe\AwaitGenerator\AwaitException: "Unhandled async exception: Position world is null or has been unloaded" (EXCEPTION) in "/home/user/pm/virions/await-generator_dev-130.phar/src/SOFe/AwaitGenerator/Await" at line 587
--- Stack trace ---
  #0 /home/user/pm/virions/await-generator_dev-130.phar/src/SOFe/AwaitGenerator/Await(334): SOFe\AwaitGenerator\Await->reject(object pocketmine\utils\AssumptionFailedError#478059)
  #1 /home/user/pm/virions/await-generator_dev-130.phar/src/SOFe/AwaitGenerator/Await(317): SOFe\AwaitGenerator\Await->wakeup(object Closure#897486)
  #2 /home/user/pm/virions/await-generator_dev-130.phar/src/SOFe/AwaitGenerator/Await(552): SOFe\AwaitGenerator\Await->wakeupFlat(object Closure#897486)
  #3 /home/user/pm/virions/await-generator_dev-130.phar/src/SOFe/AwaitGenerator/AwaitChild(52): SOFe\AwaitGenerator\Await->recheckPromiseQueue(object SOFe\AwaitGenerator\AwaitChild#130259)
  #4 /home/user/pm/virions/libasynql_dev-204.phar/src/poggit/libasynql/base/DataConnectorImpl(124): SOFe\AwaitGenerator\AwaitChild->resolve()
  #5 /home/user/pm/virions/libasynql_dev-204.phar/src/poggit/libasynql/base/DataConnectorImpl(181): poggit\libasynql\base\DataConnectorImpl::poggit\libasynql\base\{closure}(object poggit\libasynql\SqlResult#819536)
  #6 /home/user/pm/virions/libasynql_dev-204.phar/src/poggit/libasynql/base/DataConnectorImpl(239): poggit\libasynql\base\DataConnectorImpl::poggit\libasynql\base\{closure}(array[1])
  #7 /home/user/pm/virions/libasynql_dev-204.phar/src/poggit/libasynql/base/SqlThreadPool(116): poggit\libasynql\base\DataConnectorImpl->poggit\libasynql\base\{closure}(array[1])
  #8 /home/user/pm/virions/libasynql_dev-204.phar/src/poggit/libasynql/base/DataConnectorImpl(322): poggit\libasynql\base\SqlThreadPool->readResults(array[1662], null)
  #9 /home/user/pm/virions/libasynql_dev-204.phar/src/poggit/libasynql/base/SqlThreadPool(64): poggit\libasynql\base\DataConnectorImpl->checkResults()
  #10 pmsrc/vendor/pocketmine/snooze/src/SleeperHandler(120): poggit\libasynql\base\SqlThreadPool->poggit\libasynql\base\{closure}()
  #11 pmsrc/src/TimeTrackingSleeperHandler(58): pocketmine\snooze\SleeperHandler->processNotifications()
  #12 pmsrc/vendor/pocketmine/snooze/src/SleeperHandler(79): pocketmine\TimeTrackingSleeperHandler->processNotifications()
  #13 pmsrc/src/Server(1683): pocketmine\snooze\SleeperHandler->sleepUntil(float 1700069516.9339)
  #14 (): --- below is the original stack trace ---()
  #15 /home/user/pm/virions/libasynql_dev-204.phar/src/poggit/libasynql/base/DataConnectorImpl(223): poggit\libasynql\base\DataConnectorImpl->executeImplRaw(array[1], array[1], array[1], object Closure#475644, object Closure#828114)
  #16 /home/user/pm/virions/libasynql_dev-204.phar/src/poggit/libasynql/base/DataConnectorImpl(180): poggit\libasynql\base\DataConnectorImpl->executeImpl(string[29] bcp.generic.begin_transaction, array[0], int 0, object Closure#475644, object Closure#828114)
  #17 /home/user/pm/virions/libasynql_dev-204.phar/src/poggit/libasynql/base/DataConnectorImpl(122): poggit\libasynql\base\DataConnectorImpl->executeImplLast(string[29] bcp.generic.begin_transaction, array[0], int 0, object Closure#546003, object Closure#828114)
  #18 /home/user/pm/virions/libasynql_dev-204.phar/src/poggit/libasynql/base/DataConnectorImpl(132): poggit\libasynql\base\DataConnectorImpl->executeGeneric(string[29] bcp.generic.begin_transaction, array[0], object Closure#836879, object Closure#828114)
  #19 plugins/BedcoreProte/src/matcracker/BedcoreProtect/storage/queries/BlocksQueries(262): poggit\libasynql\base\DataConnectorImpl->asyncGeneric(string[29] bcp.generic.begin_transaction)
  #20 /home/user/pm/virions/await-generator_dev-130.phar/src/SOFe/AwaitGenerator/Mutex(114): matcracker\BedcoreProtect\storage\queries\BlocksQueries->matcracker\BedcoreProtect\storage\queries\{closure}()
  #21 /home/user/pm/virions/await-generator_dev-130.phar/src/SOFe/AwaitGenerator/Mutex(103): SOFe\AwaitGenerator\Mutex->run(object Generator#500597)
  #22 (): SOFe\AwaitGenerator\Mutex->runClosure(object Closure#219746)
  #23 /home/user/pm/virions/await-generator_dev-130.phar/src/SOFe/AwaitGenerator/Await(376): Generator->send(object Closure#828114)
  #24 /home/user/pm/virions/await-generator_dev-130.phar/src/SOFe/AwaitGenerator/Await(332): SOFe\AwaitGenerator\Await->SOFe\AwaitGenerator\{closure}()
  #25 /home/user/pm/virions/await-generator_dev-130.phar/src/SOFe/AwaitGenerator/Await(317): SOFe\AwaitGenerator\Await->wakeup(object Closure#191202)
  #26 /home/user/pm/virions/await-generator_dev-130.phar/src/SOFe/AwaitGenerator/Await(552): SOFe\AwaitGenerator\Await->wakeupFlat(object Closure#191202)
  #27 /home/user/pm/virions/await-generator_dev-130.phar/src/SOFe/AwaitGenerator/AwaitChild(52): SOFe\AwaitGenerator\Await->recheckPromiseQueue(object SOFe\AwaitGenerator\AwaitChild#587520)
  #28 /home/user/pm/virions/libasynql_dev-204.phar/src/poggit/libasynql/base/DataConnectorImpl(165): SOFe\AwaitGenerator\AwaitChild->resolve(array[2])
  #29 /home/user/pm/virions/libasynql_dev-204.phar/src/poggit/libasynql/base/DataConnectorImpl(156): poggit\libasynql\base\DataConnectorImpl::poggit\libasynql\base\{closure}(int 425736, int 1)
  #30 /home/user/pm/virions/libasynql_dev-204.phar/src/poggit/libasynql/base/DataConnectorImpl(181): poggit\libasynql\base\DataConnectorImpl::poggit\libasynql\base\{closure}(object poggit\libasynql\result\SqlInsertResult#731591)
  #31 /home/user/pm/virions/libasynql_dev-204.phar/src/poggit/libasynql/base/DataConnectorImpl(239): poggit\libasynql\base\DataConnectorImpl::poggit\libasynql\base\{closure}(array[1])
  #32 /home/user/pm/virions/libasynql_dev-204.phar/src/poggit/libasynql/base/SqlThreadPool(116): poggit\libasynql\base\DataConnectorImpl->poggit\libasynql\base\{closure}(array[1])
  #33 /home/user/pm/virions/libasynql_dev-204.phar/src/poggit/libasynql/base/DataConnectorImpl(322): poggit\libasynql\base\SqlThreadPool->readResults(array[2317], null)
  #34 /home/user/pm/virions/libasynql_dev-204.phar/src/poggit/libasynql/base/SqlThreadPool(64): poggit\libasynql\base\DataConnectorImpl->checkResults()
  #35 pmsrc/vendor/pocketmine/snooze/src/SleeperHandler(120): poggit\libasynql\base\SqlThreadPool->poggit\libasynql\base\{closure}()
  #36 pmsrc/src/TimeTrackingSleeperHandler(58): pocketmine\snooze\SleeperHandler->processNotifications()
  #37 pmsrc/vendor/pocketmine/snooze/src/SleeperHandler(79): pocketmine\TimeTrackingSleeperHandler->processNotifications()
  #38 pmsrc/src/Server(1683): pocketmine\snooze\SleeperHandler->sleepUntil(float 1700069506.7339)
  #39 pmsrc/src/Server(1065): pocketmine\Server->tickProcessor()
  #40 pmsrc/src/PocketMine(341): pocketmine\Server->__construct(object pocketmine\thread\ThreadSafeClassLoader#3, object pocketmine\utils\MainLogger#6, string[14] /home/user/pm/, string[22] /home/user/pm/plugins/)
  #41 pmsrc/src/PocketMine(364): pocketmine\server()
  #42 pmsrc(11): require(string[58] phar:///home/user/pm/PocketMine-MP.phar/src/PocketMine.php)
--- Previous ---
pocketmine\utils\AssumptionFailedError: "Position world is null or has been unloaded" (EXCEPTION) in "pmsrc/src/world/Position" at line 63
  #0 plugins/BedcoreProte/src/matcracker/BedcoreProtect/storage/queries/BlocksQueries(275): pocketmine\world\Position->getWorld()
  #1 /home/user/pm/virions/await-generator_dev-130.phar/src/SOFe/AwaitGenerator/Mutex(114): matcracker\BedcoreProtect\storage\queries\BlocksQueries->matcracker\BedcoreProtect\storage\queries\{closure}()
  #2 /home/user/pm/virions/await-generator_dev-130.phar/src/SOFe/AwaitGenerator/Mutex(103): SOFe\AwaitGenerator\Mutex->run(object Generator#500597)
  #3 (): SOFe\AwaitGenerator\Mutex->runClosure(object Closure#219746)
  #4 /home/user/pm/virions/await-generator_dev-130.phar/src/SOFe/AwaitGenerator/Await(553): Generator->send(null)
  #5 /home/user/pm/virions/await-generator_dev-130.phar/src/SOFe/AwaitGenerator/Await(332): SOFe\AwaitGenerator\Await->SOFe\AwaitGenerator\{closure}()
  #6 /home/user/pm/virions/await-generator_dev-130.phar/src/SOFe/AwaitGenerator/Await(317): SOFe\AwaitGenerator\Await->wakeup(object Closure#897486)
  #7 /home/user/pm/virions/await-generator_dev-130.phar/src/SOFe/AwaitGenerator/Await(552): SOFe\AwaitGenerator\Await->wakeupFlat(object Closure#897486)
  #8 /home/user/pm/virions/await-generator_dev-130.phar/src/SOFe/AwaitGenerator/AwaitChild(52): SOFe\AwaitGenerator\Await->recheckPromiseQueue(object SOFe\AwaitGenerator\AwaitChild#130259)
  #9 /home/user/pm/virions/libasynql_dev-204.phar/src/poggit/libasynql/base/DataConnectorImpl(124): SOFe\AwaitGenerator\AwaitChild->resolve()
  #10 /home/user/pm/virions/libasynql_dev-204.phar/src/poggit/libasynql/base/DataConnectorImpl(181): poggit\libasynql\base\DataConnectorImpl::poggit\libasynql\base\{closure}(object poggit\libasynql\SqlResult#819536)
  #11 /home/user/pm/virions/libasynql_dev-204.phar/src/poggit/libasynql/base/DataConnectorImpl(239): poggit\libasynql\base\DataConnectorImpl::poggit\libasynql\base\{closure}(array[1])
  #12 /home/user/pm/virions/libasynql_dev-204.phar/src/poggit/libasynql/base/SqlThreadPool(116): poggit\libasynql\base\DataConnectorImpl->poggit\libasynql\base\{closure}(array[1])
  #13 /home/user/pm/virions/libasynql_dev-204.phar/src/poggit/libasynql/base/DataConnectorImpl(322): poggit\libasynql\base\SqlThreadPool->readResults(array[1661], null)
  #14 /home/user/pm/virions/libasynql_dev-204.phar/src/poggit/libasynql/base/SqlThreadPool(64): poggit\libasynql\base\DataConnectorImpl->checkResults()
  #15 pmsrc/vendor/pocketmine/snooze/src/SleeperHandler(120): poggit\libasynql\base\SqlThreadPool->poggit\libasynql\base\{closure}()
  #16 pmsrc/src/TimeTrackingSleeperHandler(58): pocketmine\snooze\SleeperHandler->processNotifications()
  #17 pmsrc/vendor/pocketmine/snooze/src/SleeperHandler(79): pocketmine\TimeTrackingSleeperHandler->processNotifications()
  #18 pmsrc/src/Server(1683): pocketmine\snooze\SleeperHandler->sleepUntil(float 1700069516.9339)
  #19 pmsrc/src/Server(1065): pocketmine\Server->tickProcessor()
  #20 pmsrc/src/PocketMine(341): pocketmine\Server->__construct(object pocketmine\thread\ThreadSafeClassLoader#3, object pocketmine\utils\MainLogger#6, string[14] /home/user/pm/, string[22] /home/user/pm/plugins/)
  #21 pmsrc/src/PocketMine(364): pocketmine\server()
  #22 pmsrc(11): require(string[58] phar:///home/user/pm/PocketMine-MP.phar/src/PocketMine.php)
--- End of exception information ---

**Comment by matcracker** [comment]
Which version of plugin are you using?

**Comment by cherrychip8293** [comment]
> Which version of plugin are you using?

The most recent version

**Comment by matcracker** [comment]
Thanks for the report.
